### ISSUE TITLE
Tutorial 5 GLFW issue

### ISSUE THREAD

**Issue by teaganc** [Niko40/Vulkan-API-Tutorials#10]
Tutorial - 0005 - GLFW Example: main.cpp: line 82 
should read 
    instance_create_info.enabledExtensionCount      = instance_extensions.size();
instead of 
    instance_create_info.enabledLayerCount          = instance_extensions.size();

**Comment by Noxagonal** [comment]
Thanks for reporting. Fixed in master. :)
